spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/your_db_name
    username: your-db-username
    password: your-db-password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

notification:
  solapi:
    api-key: your-solapi-api-key
    api-secret: your-solapi-api-secret
    from-number: "01000000000"
  nurigo:
    api-key: your-nurigo-api-key
    api-secret: your-nurigo-api-secret
    from-number: "01000000000"
  ses:
    region: ap-northeast-2
    from-email: no-reply@your-domain.com
  fingerpush:
    api-key: your-fingerpush-api-key
    app-id: your-app-id
  slack:
    webhook-url: ""
  stage:
    allowed-domains:
      - example.com
      - test.com